rulenumber:
  db:
    url: jdbc:mysql://127.0.0.1:3306/common_util?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=True&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: 307860
