CREATE TABLE TBL_NUMBER_GENERATOR_RULE
(
    rule_id     BIGINT NOT NULL COMMENT '规则Id',
    rule_name   NVARCHAR(50) COMMENT '规则名称',
    description NVARCHAR(500) COMMENT '规则描述',
    valid       NVARCHAR(1) DEFAULT 'Y' COMMENT '生效标识'
) COMMENT '规则定义表';
ALTER TABLE TBL_NUMBER_GENERATOR_RULE
    ADD CONSTRAINT KEY_TBL_NUMBER_GENERATOR_RULE PRIMARY KEY (rule_id);
